spring.application.name=backend-assignment

# MSSQL Database Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TESTDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=YourStrong!Passw0rd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.web=INFO
logging.level.com.interview.backend=INFO
logging.file.name=logs/api-requests.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
